spring.application.name=backend
spring.datasource.url=Your_DB_URL
spring.datasource.username=Your_DB_USERNAME
spring.datasource.password=Your_DB_Password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Optional: Automatically create/update tables
spring.jpa.hibernate.ddl-auto=update
hashids.text = hashids_text
hashids.min-length = hashids_minimum_length